### ISSUE TITLE
Missing dependencies specification? 

### ISSUE THREAD

**Issue by Fishrock123** [Vespher/PhorceBot-Framework#1]
I assume that pip or PyPI have some kind of dependency specification file similar to Node.js's`package.json`, etc - that seems like it would be helpful here, since it seems like `irc` in the source has to come from somewhere? 
_(Note: I am not very proficient with python and could be misunderstanding.)_

**Comment by Vespher** [comment]
Nope - the connection is made using socket, which is included in python
installations.
